baseURL = "https://kkato.dev/"
defaultContentLanguage = ["ja", "en"]
languageCode = "en"
title = "kkato.dev"
theme = "LoveIt"

[author]
  name = "Ken Kato"
  email = "kkato149@gmail.com"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "Posts"
    name = "Posts"
    url = "/posts/"
    title = "Posts - kkato.dev"
  [[menu.main]]
    weight = 2
    identifier = "Categories"
    name = "Categories"
    url = "/categories/"
    title = "Categories - kkato.dev"
  [[menu.main]]
    weight = 3
    identifier = "Tags"
    name = "Tags"
    url = "/tags/"
    title = "Tags - kkato.dev"
  [[menu.main]]
    weight = 4
    identifier = "Talks"
    name = "Talks"
    url = "/talks/"
    title = "Talks - kkato.dev"
  [[menu.main]]
    weight = 5
    identifier = "Portofolio"
    name = "Portfolio"
    url = "/portofolio/"
    title = "Portfolio - kkato.dev"
  [[menu.main]]
    weight = 6
    identifier = "About"
    name = "About"
    url = "/about"
    title = "About - kkato.dev"

[params]
  images = ["images/sagarifuji.png"]
  [params.header]
    [params.header.title]
      name = "kkato.dev"
      pre = "<i class='fas fa-caret-right' aria-hidden='true'></i>"
  [params.footer]
    enable = true
    hugo = true
    copyright = true
    author = true
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  [params.search]
    enable = true
  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      avatarURL = "/images/sagarifuji.png"
      subtitle = "Ken Kato's web site"
      typeit = true
      social = true
    [params.home.posts]
      enable = true
      pagenate = 6
  [params.social]
    GitHub = "kkato"
    Linkedin = "ken-kato"

[languages.ja]
weight = 1
languageCode = "ja"
languageName = '日本語'
hasCJKLanguage = true

[languages.en]
weight = 2
languageCode = "en-us"
languageName = 'English'
hasCJKLanguage = false